const ClaimContact = require("./ClaimContact");
const ClaimDocument = require("./ClaimDocument");
const ClaimContactRole = require("./typelist/ClaimContactRole");

module.exports = {
  Account: require("./Account"),
  Address: require("./Address"),
  Contact: require("./Contact"),
  Coverage: require("./Coverage"),
  Driver: require("./Driver"),
  Group: require("./Group"),
  Job: require("./Job"),
  Organization: require("./Organization"),
  ProducerCode: require("./ProducerCode"),
  Term: require("./Term"),
  User: require("./User"),
  Vehicle: require("./Vehicle"),
  Policy: require("./Policy"),
  RecentlyViewed: require("./RecentlyViewed"),
  Activity: require("./Activity"),
  ContactType: require("./typelist/ContactType"),
  Country: require("./typelist/Country"),
  Currency: require("./typelist/Currency"),
  UserType: require("./typelist/UserType"),
  AccountStatus: require("./typelist/AccountStatus"),
  ContactRole: require("./typelist/ContactRole"),
  State: require("./typelist/State"),
  JobType: require("./typelist/JobType"),
  JobStatus: require("./typelist/JobStatus"),
  Product: require("./typelist/Product"),
  BodyType: require("./typelist/BodyType"),
  PolicyStatus: require("./typelist/PolicyStatus"),
  LossCause: require("./typelist/LossCause"),
  ClaimStatus: require("./typelist/ClaimStatus"),
  AffectedAreas: require("./typelist/AffectedAreas"),
  Claim: require("./Claim"),
  ClaimContact: require("./ClaimContact"),
  ClaimContactRole: require("./typelist/ClaimContactRole"),
  DocumentSecurityType: require("./typelist/DocumentSecurityType"),
  ClaimDocument: require("./ClaimDocument"),
};
