module.exports = {
  Account: require('./Account'),
  Address: require('./Address'),
  Contact: require('./Contact'),
  Coverage: require('./Coverage'),
  Driver: require('./Driver'),
  Group: require('./Group'),
  Job: require('./Job'),
  Organization: require('./Organization'),
  ProducerCode: require('./ProducerCode'),
  Term: require('./Term'),
  User: require('./User'),
  Vehicle: require('./Vehicle'),
  ContactType: require('./typelist/ContactType'),
  Country: require('./typelist/Country'),
  Currency: require('./typelist/Currency'),
  UserType: require('./typelist/UserType'),
  AccountStatus: require('./typelist/AccountStatus'),
  ContactRole: require('./typelist/ContactRole'),
  State: require('./typelist/State'),
  JobType: require('./typelist/JobType'),
  JobStatus: require('./typelist/JobStatus'),
  Product: require('./typelist/Product'),
};